# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    owm.api_key: '%env(string:OWM_API_KEY)%'
    owm.country_code: '%env(string:OWM_COUNTRY_CODE)%'
    owm.unit_code: '%env(string:OWM_UNIT_CODE)%'
    owm.base_url: '%env(string:OWM_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    App\EventListener\UserPasswordHasherListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    # Import automatique de tes classes
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\MeteoClient:
        autowire: false       # ⛔ désactive l’autowiring automatique
        autoconfigure: false
        arguments:
            $http: '@http_client'
            $meteoCache: '@meteo.cache'
            $apiKey: '%owm.api_key%'
            $countryCode: '%owm.country_code%'
            $unitCode: '%owm.unit_code%'
            $baseUrl: '%owm.base_url%'
            $logger: '@logger'
